# Generated by Django 5.0.3 on 2024-03-12 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('job_title', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('github_url', models.URLField()),
                ('city', models.CharField(max_length=255)),
                ('birth_date', models.DateField()),
                ('university', models.CharField(max_length=255)),
                ('introduction', models.TextField()),
                ('skillset', models.TextField()),
                ('rewards', models.TextField()),
                ('projects', models.TextField()),
                ('results', models.TextField()),
            ],
        ),
    ]
